### PR TITLE
feat: add progress bar

### PR DESCRIPTION
**Pull request by h3nill**
- [x] bench
- [x] conformance
- [x] simulator
- [ ] round
- [ ] test

### CODE REVIEW

**Comment by mnpw** [comment]
We can skip `round` and `test` for this. For `conformance` we should add a progress bar that moves a step up after ever test is completed.

So if there are N tests in `conformance`, the progress bar goes from 0..N

**Comment by h3nill** [comment]
for now had to set value of N manually because no easy way to calculate how many tests we are going to run.

**Comment by mnpw** [comment]
> for now had to set value of N manually because no easy way to calculate how many tests we are going to run.

a. Is it possible to collect all tests in `conformance::basic` in a collection and then use the iterator of that collection for showing progress? (maybe something like [this](https://docs.rs/indicatif/0.17.3/indicatif/index.html#iterators)?)

b. Also, instead of initializing a progress bar in `conformance` and passing it to each test in `conformance::basic`, we can create a static item (`once_cell::sync::Lazy`) in `conformance::basic` and use without unnecessarily complicating the signature of all tests

**Comment by henil** [comment]
> a. Is it possible to collect all tests in conformance::basic in a collection and then use the iterator of that collection for showing progress? (maybe something like [this](https://docs.rs/indicatif/0.17.3/indicatif/index.html#iterators)?)

there might be a way to do this but because this test functions are async, collecting in a collection would be ugly and because number of tests are finite its fine to just increment that number when we add a new test.

**Comment by h3nill** [comment]
> a. Is it possible to collect all tests in conformance::basic in a collection and then use the iterator of that collection for showing progress? (maybe something like [this](https://docs.rs/indicatif/0.17.3/indicatif/index.html#iterators)?)

there might be a way to do this but because this test functions are async, collecting in a collection would be ugly and because number of tests are finite its fine to just increment that number when we add a new test.

**Comment by h3nill** [comment]
Merging because we need to deploy, will make a new PR for any new changes

**Pull request merged**
